// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Temperatura.Web.Data;

#nullable disable

namespace Temperatura.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812210129_AddConfiguracionSmtp")]
    partial class AddConfiguracionSmtp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a83bce0d-b0dc-4a0f-bb38-2d58fce2c001",
                            ConcurrencyStamp = "a83bce0d-b0dc-4a0f-bb38-2d58fce2c001",
                            Name = "Registrador",
                            NormalizedName = "REGISTRADOR"
                        },
                        new
                        {
                            Id = "a83bce0d-b0dc-4a0f-bb38-2d58fce2c002",
                            ConcurrencyStamp = "a83bce0d-b0dc-4a0f-bb38-2d58fce2c002",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ambientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Farmacia"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "UMA 1"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "UMA 2"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "UMA 3"
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.AmbienteHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<short>("MinutosAntes")
                        .HasColumnType("smallint");

                    b.Property<short>("MinutosDespues")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("AmbienteId", "HorarioId")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("AmbienteId", "HorarioId", "VigenteDesde")
                        .IsUnique();

                    b.ToTable("AmbientesHorarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_AmbientesHorarios_Ventana", "[MinutosAntes] >= 0 AND [MinutosDespues] > 0");

                            t.HasCheckConstraint("CK_AmbientesHorarios_Vigencia", "[VigenteHasta] IS NULL OR [VigenteHasta] >= [VigenteDesde]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AmbienteId = 1,
                            HorarioId = 1,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            AmbienteId = 1,
                            HorarioId = 2,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AmbienteId = 1,
                            HorarioId = 3,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            AmbienteId = 2,
                            HorarioId = 1,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            AmbienteId = 2,
                            HorarioId = 2,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            AmbienteId = 2,
                            HorarioId = 3,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            AmbienteId = 2,
                            HorarioId = 4,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            AmbienteId = 3,
                            HorarioId = 1,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            AmbienteId = 3,
                            HorarioId = 2,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            AmbienteId = 3,
                            HorarioId = 3,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            AmbienteId = 3,
                            HorarioId = 4,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            AmbienteId = 4,
                            HorarioId = 1,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            AmbienteId = 4,
                            HorarioId = 2,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            AmbienteId = 4,
                            HorarioId = 3,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            AmbienteId = 4,
                            HorarioId = 4,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            AmbienteId = 5,
                            HorarioId = 1,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            AmbienteId = 5,
                            HorarioId = 2,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            AmbienteId = 5,
                            HorarioId = 3,
                            MinutosAntes = (short)30,
                            MinutosDespues = (short)60,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.AmbienteMedicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("RangoMaximo")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("RangoMinimo")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("TipoMedicionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TipoMedicionId");

                    b.HasIndex("AmbienteId", "TipoMedicionId")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("AmbienteId", "TipoMedicionId", "VigenteDesde")
                        .IsUnique();

                    b.ToTable("AmbientesMediciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_AmbientesMediciones_Rango", "[RangoMinimo] <= [RangoMaximo]");

                            t.HasCheckConstraint("CK_AmbientesMediciones_Vigencia", "[VigenteHasta] IS NULL OR [VigenteHasta] >= [VigenteDesde]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AmbienteId = 1,
                            RangoMaximo = 26m,
                            RangoMinimo = 18m,
                            TipoMedicionId = 1,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            AmbienteId = 1,
                            RangoMaximo = 70m,
                            RangoMinimo = 30m,
                            TipoMedicionId = 2,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AmbienteId = 1,
                            RangoMaximo = 8m,
                            RangoMinimo = 2m,
                            TipoMedicionId = 3,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            AmbienteId = 2,
                            RangoMaximo = 8m,
                            RangoMinimo = 2m,
                            TipoMedicionId = 3,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            AmbienteId = 3,
                            RangoMaximo = 26m,
                            RangoMinimo = 18m,
                            TipoMedicionId = 1,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            AmbienteId = 3,
                            RangoMaximo = 70m,
                            RangoMinimo = 30m,
                            TipoMedicionId = 2,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            AmbienteId = 3,
                            RangoMaximo = 8m,
                            RangoMinimo = 2m,
                            TipoMedicionId = 3,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            AmbienteId = 4,
                            RangoMaximo = 26m,
                            RangoMinimo = 18m,
                            TipoMedicionId = 1,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            AmbienteId = 4,
                            RangoMaximo = 70m,
                            RangoMinimo = 30m,
                            TipoMedicionId = 2,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            AmbienteId = 4,
                            RangoMaximo = 8m,
                            RangoMinimo = 2m,
                            TipoMedicionId = 3,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            AmbienteId = 5,
                            RangoMaximo = 26m,
                            RangoMinimo = 18m,
                            TipoMedicionId = 1,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            AmbienteId = 5,
                            RangoMaximo = 70m,
                            RangoMinimo = 30m,
                            TipoMedicionId = 2,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            AmbienteId = 5,
                            RangoMaximo = 8m,
                            RangoMinimo = 2m,
                            TipoMedicionId = 3,
                            VigenteDesde = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Temperatura.Web.Domain.ConfiguracionSmtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ActualizadoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorreoRemitente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreRemitente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.Property<string>("SecretoProtegido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Servidor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("UsarTls")
                        .HasColumnType("bit");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesSmtp", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConfiguracionesSmtp_Puerto", "[Puerto] BETWEEN 1 AND 65535");

                            t.HasCheckConstraint("CK_ConfiguracionesSmtp_RegistroUnico", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.DetalleRegistro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AmbienteMedicionId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoRango")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("LimiteMaximoAplicado")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("LimiteMinimoAplicado")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoMedicionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteMedicionId");

                    b.HasIndex("TipoMedicionId");

                    b.HasIndex("RegistroId", "TipoMedicionId")
                        .IsUnique();

                    b.ToTable("DetallesRegistro", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetallesRegistro_Limites", "[LimiteMinimoAplicado] <= [LimiteMaximoAplicado]");
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsCierreDiaOperativoAnterior")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("HoraReferencia")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HoraReferencia")
                        .IsUnique();

                    b.ToTable("Horarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EsCierreDiaOperativoAnterior = false,
                            HoraReferencia = new TimeOnly(7, 0, 0),
                            Nombre = "07:00"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            EsCierreDiaOperativoAnterior = false,
                            HoraReferencia = new TimeOnly(12, 0, 0),
                            Nombre = "12:00"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            EsCierreDiaOperativoAnterior = false,
                            HoraReferencia = new TimeOnly(19, 0, 0),
                            Nombre = "19:00"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            EsCierreDiaOperativoAnterior = true,
                            HoraReferencia = new TimeOnly(0, 0, 0),
                            Nombre = "00:00"
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Registro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("FechaHoraRegistro")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("FechaOperativa")
                        .HasColumnType("date");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<string>("Puntualidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("FechaOperativa", "AmbienteId");

                    b.HasIndex("AmbienteId", "HorarioId", "FechaOperativa")
                        .IsUnique();

                    b.ToTable("Registros", (string)null);
                });

            modelBuilder.Entity("Temperatura.Web.Domain.TipoMedicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte>("DecimalesPermitidos")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SimboloUnidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposMedicion", null, t =>
                        {
                            t.HasCheckConstraint("CK_TiposMedicion_Decimales", "[DecimalesPermitidos] BETWEEN 0 AND 4");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            DecimalesPermitidos = (byte)1,
                            Nombre = "Temperatura ambiental",
                            SimboloUnidad = "°C"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            DecimalesPermitidos = (byte)1,
                            Nombre = "Humedad relativa",
                            SimboloUnidad = "%"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            DecimalesPermitidos = (byte)1,
                            Nombre = "Temperatura de refrigeración",
                            SimboloUnidad = "°C"
                        });
                });

            modelBuilder.Entity("Temperatura.Web.Domain.UsuarioAmbiente", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId", "AmbienteId");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[EsPredeterminado] = 1 AND [Activo] = 1");

                    b.ToTable("UsuariosAmbientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_UsuariosAmbientes_PredeterminadoActivo", "[EsPredeterminado] = 0 OR [Activo] = 1");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Temperatura.Web.Domain.AmbienteHorario", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.Ambiente", "Ambiente")
                        .WithMany("Horarios")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.Horario", "Horario")
                        .WithMany("Ambientes")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.AmbienteMedicion", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.Ambiente", "Ambiente")
                        .WithMany("Mediciones")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.TipoMedicion", "TipoMedicion")
                        .WithMany("Ambientes")
                        .HasForeignKey("TipoMedicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("TipoMedicion");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.DetalleRegistro", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.AmbienteMedicion", "AmbienteMedicion")
                        .WithMany("Detalles")
                        .HasForeignKey("AmbienteMedicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.Registro", "Registro")
                        .WithMany("Detalles")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.TipoMedicion", "TipoMedicion")
                        .WithMany("Detalles")
                        .HasForeignKey("TipoMedicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmbienteMedicion");

                    b.Navigation("Registro");

                    b.Navigation("TipoMedicion");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Registro", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.Ambiente", "Ambiente")
                        .WithMany("Registros")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.Horario", "Horario")
                        .WithMany("Registros")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.ApplicationUser", "Usuario")
                        .WithMany("Registros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("Horario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.UsuarioAmbiente", b =>
                {
                    b.HasOne("Temperatura.Web.Domain.Ambiente", "Ambiente")
                        .WithMany("Usuarios")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temperatura.Web.Domain.ApplicationUser", "Usuario")
                        .WithMany("Ambientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Ambiente", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Mediciones");

                    b.Navigation("Registros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.AmbienteMedicion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.ApplicationUser", b =>
                {
                    b.Navigation("Ambientes");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Horario", b =>
                {
                    b.Navigation("Ambientes");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.Registro", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Temperatura.Web.Domain.TipoMedicion", b =>
                {
                    b.Navigation("Ambientes");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
